/**
 * Fetch AmazonProductData
 *
 * @return Table of product data with specified columns
 * @customfunction
 */
function getAmazonProductData() {
    return teamcartgs.core.get_amazon_product_data.apply(null, arguments);
}

/**
 * 
 *
 * @return Checkout link for selection
 * @customfunction
 */
function getTeamcartCheckoutLink() {
    return teamcartgs.core.get_checkout_link.apply(null, arguments);
}

/**
 * 
 *
 * @return Checkout link for selection
 * @customfunction
 */
function teamcartTest() {
    return teamcartgs.core.teamcart_test.apply(null, arguments);
}

/**
 * Note: The code below is generated by the Clojurescript compiler.
 */
