/**
 * Copyright TeamCart 2016
 * Usage is subject to Terms of Service and Privacy Policy specified on https://teamcart.io/
 */

/**
 * Fetch AmazonProductData
 *
 * @param {range} Range for product urls to fetch
 * @param {range} Range for product data keys to display
 * @return Table of product data with specified columns
 * @customfunction
 */
function getAmazonProductData() {
    return teamcartgs.core.get_amazon_product_data.apply(null, arguments);
}

/**
 * Get checkout link for given cart
 *
 * @param {range} Range of product ids to include in cart
 * @param {range} Range of quantities corresponding to product ids
 * @return Checkout link for selected ranges
 * @customfunction
 */
function getTeamcartCheckoutLink() {
    return teamcartgs.core.get_checkout_link.apply(null, arguments);
}

/**
 * The code below is generated by the Clojurescript compiler.
 */
